name = "sns-marketing-manager"
compatibility_date = "2026-09-20"

[[d1_databases]]
binding = "DB"
database_name = "sns-marketing-manager-local"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"
